package ec.edu.espe.bank.view;

/**
 *
 * @author TOSHIBA
 */
public class FrmInformation extends javax.swing.JFrame {

    /**
     * Creates new form FrmInformation
     */
    public FrmInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblGuide = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblCdt = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lblSaving = new javax.swing.JLabel();
        lblChecking = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        bnReturn = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setText("Welcome to Banking Plan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 170, 30));

        jLabel3.setText("Banking Plan is  a program that helps to improve the mismanagement of a person's");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 500, 30));

        jLabel4.setText("from the control of their expenses so as to avoid losing money or even going bankrupt.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 580, 20));

        jLabel5.setText("Banking Plan will contribute to society since it is a system that will help us to administer");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 184, 530, 20));

        jLabel6.setText("money correctly. The program is a banking simulation where you will know the amount of");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 550, -1));

        jLabel7.setText("money you have in your account, thus separating it into: Savings Account, Checking Account,  ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 214, 650, 20));

        jLabel8.setText("and their respective interest generated monthly and annually.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 370, -1));

        lblId.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ID.PNG"))); // NOI18N
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 260, -1));

        jLabel10.setText("   1)  Enter age");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel11.setText("2)  Enter User Name");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel12.setText("3)  You need to create an id");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel13.setText("4)  You need to create a password");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jLabel14.setText("5)  Click on register");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        lblGuide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GUIA.PNG"))); // NOI18N
        lblGuide.setText("jLabel2");
        jPanel1.add(lblGuide, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 180, 100));

        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NAME.PNG"))); // NOI18N
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 260, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SAVING.PNG")));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, 20));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SAVING.PNG")));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SAVING.PNG")));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, 30));

        lblAge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AGE.PNG"))); // NOI18N
        jPanel1.add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 260, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel21.setText("How to enter ?");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 90, -1));

        jLabel22.setText("1)  Enter User Name");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        jLabel23.setText("2)  Enter your password");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, -1, -1));

        jLabel24.setText("    3)  Click on Login");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel16.setText("Accounts");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 60, -1));

        jLabel25.setText("To open your account you need to register. ");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, -1, 20));

        jLabel26.setText("In this account you can save your money and have it at the time you require");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel27.setText("Savings Account");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 100, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel28.setText("Checking Account");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, 110, -1));

        jLabel29.setText("To open your account you need to register.");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, -1, -1));

        jLabel30.setText("To request this account you need a specific amount of money");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, -1, -1));

        lblCdt.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblCdt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CDT_1.PNG"))); // NOI18N
        jPanel1.add(lblCdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 140, -1));

        jLabel34.setText("To open your account you need to register.");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 670, -1, -1));

        lblSaving.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SAVING.PNG"))); // NOI18N
        jPanel1.add(lblSaving, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 210, 110));

        lblChecking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CHEC.PNG"))); // NOI18N
        jPanel1.add(lblChecking, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 250, 130));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SAVING.PNG")));
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 140, -1));

        lblPassword.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CONTRA.PNG"))); // NOI18N
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 260, -1));

        lblRegister.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/R.PNG"))); // NOI18N
        jPanel1.add(lblRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 100, 30));

        bnReturn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bnReturn.setText("Return");
        bnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnReturnActionPerformed(evt);
            }
        });
        jPanel1.add(bnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 650, 120, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel38.setText("How to register ?");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 110, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel39.setText("CDT");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnReturnActionPerformed
       FrmAccount open = new FrmAccount();
        open.setVisible(true);
        this.setVisible (false);
    }//GEN-LAST:event_bnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCdt;
    private javax.swing.JLabel lblChecking;
    private javax.swing.JLabel lblGuide;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblSaving;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
